#!/bin/dash

# EXISTENCE THINGS
# exists in some commit but does not exist in index and root:    deleted
# exist in index and some commit but not in root:               file deleted

# file doesnt exist in any commit but added:     added to index
# file doesnt exist in any commit and not added: untracked

# DIFF THINGS
# same as currentCommit:                   same as repo 
# file diff to currComm and added:         file changed, changes staged for commit
# file diff to currComm but NOT added:     file changed, changes not staged for commit 

REPONAME=".pig"
fileWrite="$REPONAME/status"
>"$fileWrite"
CURCOM=$(ls $REPONAME/commits | grep commit | sort -r | head -1)

# find ./"$REPONAME" -type f | rev | cut -d'/' -f1 | rev | sort -u

# i check for files in root and files in the current commit
# AND OF COURSE I FORGOT TO CHECK IF THEY EXIST IN NEITHER BUT EXISTS IN INDEX AAAAAA
# IT NEED TO BE LIKE IF ONLY IN INDEX THE NU KNOW IT WAS DELETED lkjfsdakjasfjkl

# Files that still exist in root
for filename in *
do
    if [ "$filename" != "*" ]; then
        # Making sure not empty directory
        if ! find ./"$REPONAME/commits/$CURCOM" -type f | rev | cut -d'/' -f1 | rev | sort -u | grep "$filename" > /dev/null; then
            # Doesn't exist in HEAD COMMIT
            if find ./"$REPONAME/index" -type f | rev | cut -d'/' -f1 | rev | sort -u | grep "$filename" > /dev/null; then
                # Exists in INDEX
                if [ -z "$(diff "./$filename" "$REPONAME/index/$filename")" ]; then
                    # file not changed
                    echo "$filename - added to index" >> "$fileWrite"
                else
                    #file changed
                    echo "$filename - added to index, file changed" >> "$fileWrite"
                fi
            else
                echo "$filename - untracked" >> "$fileWrite"
            fi
        fi
    fi
done

for filename in $(find ./"$REPONAME/commits/$CURCOM" -type f | rev | cut -d'/' -f1 | rev | sort -u)
do
    # File exists in a commit
    if [ -f "$filename" ]; then
        # Exists in root
        diffWorkRepo=false

        if [ -f "$REPONAME/commits/$CURCOM/$filename" ]; then
            if [ -z "$(diff "./$filename" "$REPONAME/commits/$CURCOM/$filename")" ]; then
                echo "$filename - same as repo" >> "$fileWrite"
            else
                diffWorkRepo=true
            fi
        else
            # File changed due to it just being new ig
            diffWorkRepo=true
        fi

        if $diffWorkRepo; then
            if [ -f "$REPONAME/index/$filename" ]; then
                if [ -z "$(diff "./$filename" "$REPONAME/index/$filename")" ]; then
                    # Work diff from repo, same as in INDEX
                    echo "$filename - file changed, changes staged for commit" >> "$fileWrite"
                else
                    if [ -f "$REPONAME/commits/$CURCOM/$filename" ]; then
                        if [ -z "$(diff "$REPONAME/index/$filename" "$REPONAME/commits/$CURCOM/$filename")" ]; then
                            # Work diff from repo, index same as repo
                            echo "$filename - file changed, changes not staged for commit" >> "$fileWrite"
                        else
                            # Work diff from repo, then index diff from repo
                            echo "$filename - file changed, different changes staged for commit" >> "$fileWrite"
                        fi
                    fi                    
                fi
            else
                # Work diff from repo, not in INDEX
                echo "$filename - deleted from index" >> "$fileWrite"
            fi
        fi

    elif find ./"$REPONAME/index" -type f | rev | cut -d'/' -f1 | rev | sort -u | grep "$filename" > /dev/null; then
        # Exists in INDEX, does not exist in root, exists in a commit
        echo "$filename - file deleted" >> "$fileWrite"
    else
        # Does not exist in INDEX or root
        echo "$filename - file deleted, deleted from index" >> "$fileWrite"
    fi
done

# now we have checked files that exist in only root, and files that only exist in commits.
# check files that exist only in index and nowhere else
# status contains files that exist in either root or some commit
for filepath in "$REPONAME/index"/*
do
    if [ "$filepath" != "$REPONAME/index/*" ]; then
        addedAndDelete=true
        filename=$(echo "$filepath" | rev | cut -d"/" -f1 | rev)
        cat $REPONAME/status | cut -d" " -f1 > tmpfile
        while read statusedFile
        do
            if [ "$filename" = "$statusedFile" ]; then
                addedAndDelete=false
            fi
        done < tmpfile
        rm tmpfile

        # if it exist in index but not status, then it was added but file deleted
        if "$addedAndDelete"; then
            echo "$filename - added to index, file deleted" >> "$fileWrite"
        fi
    fi
done

cat $fileWrite | sort
