#!/bin/dash

# EXISTENCE THINGS
# exists in some commit but does not exist in index and root:    deleted
# exist in index and some commit but not in root:               file deleted

# file doesnt exist in any commit but added:     added to index
# file doesnt exist in any commit and not added: untracked

# DIFF THINGS
# same as currentCommit:                   same as repo 
# file diff to currComm and added:         file changed, changes staged for commit
# file diff to currComm but NOT added:     file changed, changes not staged for commit 

REPONAME=".pig"
# find ./"$REPONAME" -type f | rev | cut -d'/' -f1 | rev | sort -u
for filename in *
do
    if ! find ./"$REPONAME" -type f | rev | cut -d'/' -f1 | rev | sort -u | grep "$filename" > /dev/null; then
        echo "$filename - untracked"
    fi
done