#!/bin/dash

REPONAME=".pig"

if [ -d "$REPONAME" ]; then
	:
else
	echo "$0: error: pigs repository directory .pig not found" >& 2
	exit 1
fi

filename="$(echo "$1" | cut -d':' -f2)"

if echo "$1" | grep -qE '.+:.+'; then
	:
else
	echo "$0: error: should have arguments in style [commit number]:[filename]" >& 2
	exit 1
fi

if [ "$(echo "$1" | cut -d':' -f1)" = "" ]; then
	#NO COMMIT GIVEN
	if [ -f "$REPONAME/index/$filename" ]; then
		cat "$REPONAME/index/$filename"
	else
		echo "$0: error: '$filename' not found in index" >& 2
		exit 1
	fi
	
	
else	
	#COMMIT GIVEN
	COMMIT="$(echo "$1" | cut -d':' -f1)"
	if echo "$COMMIT" | grep -qE '^[0-9]+$'; then
		if [ -d "$REPONAME/commits/commit$COMMIT" ]; then
			if [ -f "$REPONAME/commits/commit$COMMIT/$filename" ]; then
				cat "$REPONAME/commits/commit$COMMIT/$filename"
			else
				echo "$0: error: '$filename' not found in commit $COMMIT" >& 2
				exit 1
			fi
		else
			echo "$0: error: unknown commit '$COMMIT'" >& 2
			exit 1
		fi
	else
		echo "$0: error: commit has to be a non-negative integer"
	fi

	
	
fi
