#!/bin/dash

REPONAME=".pig"

if [ -d "$REPONAME" ]; then
	:
else
	echo "$0: error: pigs repository directory .pig not found" >& 2
	exit 1
fi

case $# in
	2)
		CHECK=$1
		MESSAGE=$2
		HASA="-a"
		;;
	3)
		CHECK=$2
		MESSAGE=$3
		HASA=$1
		;;
	*)
		echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
		exit 1
esac


if [ "$CHECK" != "-m" ]; then
	echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
	exit 1
fi

if [ "$HASA" != "-a" ]; then
	echo "./$0: error: should have arguments in style [-a] -m [commit-message]" >& 2
	exit 1
else
	if  [ "$#" -ne 2 ]; then
		for filename in ./*
		do
			if [ -f "$REPONAME/index/$filename" ]; then
				cp "$filename" "$REPONAME/index/$filename"
			fi
		done
	fi
fi

if [ -z "$(ls -A $REPONAME/index)" ] && [ -z "$(ls -A $REPONAME/commits)" ]; then
	echo "nothing to commit"
	exit 1
fi

# Check if MESSAGE is assigned a value.
if [ -z "$MESSAGE" ]; then
    echo "./$0: error: message argument is not assigned a value" >&2
    exit 1
fi

CURCOM=$(wc -l "$REPONAME"/log | cut -d' ' -f1)

if [ "$CURCOM" -ne 0 ]; then
	#not first commit
	if [ -d "$REPONAME/commits/commit$CURCOM" ]; then
		#HEY THIS COMMIT ALREADY HAPPENED??
		echo "this commit already happened dummy you muistve deleted an old commit file somehow dork"
	else
		PREVCOM=$((CURCOM - 1))
		if [ "$(diff -rq "$REPONAME/commits/commit$PREVCOM" "$REPONAME/index")" ]; then
			echo "$CURCOM" "$MESSAGE" | cat - $REPONAME/log > temp && mv temp $REPONAME/log
			mkdir $REPONAME/commits/commit"$CURCOM"
			if [ "$(ls -A $REPONAME/index)" ]; then
				cp -r $REPONAME/index/* $REPONAME/commits/commit"$CURCOM"
			fi
			echo Committed as commit "$CURCOM"
		else
			#IDENTICAL
			echo nothing to commit
		fi
	fi
else
	#FIRST COMMIT
	echo "$CURCOM" "$MESSAGE" | cat - $REPONAME/log > temp && mv temp $REPONAME/log
	mkdir $REPONAME/commits/commit"$CURCOM"
	cp -r $REPONAME/index/* $REPONAME/commits/commit"$CURCOM"
	echo Committed as commit "$CURCOM"
fi
